### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oleg14038** [SENATOROVAI/senatorov#1]
### Checklist

- [X] I added a descriptive title.
- [X] I searched through [existing issues](https://t.me/c/1937296927/3602/25534) and couldn't find a solution or duplicate issue.
- [X] I searched on the web (e.g. Google) or [chatGPT](https://t.me/c/1937296927/2415/23729) and didn't find any helpful information.

### Attach a full screenshot and write what did you do to fix the problem?

При загрузки  скришота  в бот Senatorov телеграмм выдает ошибку 
![photo_2024-11-22_17-47-08](https://github.com/user-attachments/assets/d2a6561b-fefc-4fab-89b3-60716c02a45b)
![photo_2024-11-22_17-53-46](https://github.com/user-attachments/assets/2f02b033-d93b-4329-ba27-52c1b1cab875)

### Error from the terminal / Code

Произошла ошибка при обработке фото. Пожалуйста, попробуйте отправить его еще раз.
![photo_2024-11-22_17-47-08](https://github.com/user-attachments/assets/f0aecde3-94a8-4b99-a691-fea8c87d1b85)

![photo_2024-11-22_17-53-46](https://github.com/user-attachments/assets/a3d3be0b-ab8e-4ab7-9f61-a5971f5eaa7a)

### Expected behavior

Произошла ошибка при обработке фото. Пожалуйста, попробуйте отправить его еще раз.

### Actual behavior

Произошла ошибка при обработке фото. Пожалуйста, попробуйте отправить его еще раз.

**Comment by ruslansenatorov** [comment]
ОЛЕГ НАЗВАНИЕ ДОЛЖНО БЫТЬ ИНФОРМАТИВНЫМ 
![image](https://github.com/user-attachments/assets/d5c166e1-4776-4cb6-986e-70af31d7f325)

**Comment by oleg14038** [comment]
Не знал что написать

**Comment by ruslansenatorov** [comment]
closes #1
